# Generated by Django 3.2.9 on 2021-11-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='co_author',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
