# Generated by Django 3.2.9 on 2021-11-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_loan_loan_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='borrowed_time',
        ),
        migrations.AddField(
            model_name='loan',
            name='borrowed_days',
            field=models.IntegerField(default=0),
        ),
    ]
