# Generated by Django 3.2.9 on 2021-12-14 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='borrowed_days',
        ),
        migrations.AddField(
            model_name='loan',
            name='return_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='books.book'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
